name: Deploy
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Deploy to Orbiter
              uses: orbiterhost/orbiter-github-actions@v0.1.4

              with:
                  project-name: "mvc"
                  build-dir: "./dist"
                  api-key: ${{ secrets.ORBITER_KEY }}
                  node-version: "20.x"
                  build-command: "npm run build"
